# Note that the following stanza uses CircleCI 2.1 to make use of a Reusable Executor
# This allows defining a docker image to reuse across jobs.
# visit https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors to learn more.
# batoy comments
# https://circleci.com/docs/2.0/language-scala
# https://circleci.com/docs/2.0/local-cli
# https://circleci.com/developer/images
# https://circleci.com/developer/orbs/orb/okode/common
# circleci local execute --job pre-integration-build

version: 2.1

executors:
  scala-builder:
    docker:
      - image: cimg/openjdk:11.0.2
    environment:
      - SBT_VERSION: 1.2.8
    working_directory: ~/sbt-with-new-jdk
jobs:
  pre-integration-build:
    executor: scala-builder
    environment:
      SBT_OPTS: -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
    steps:
      - checkout
      - run: java --version
      - run:
          name: Installing SDKMAN!
          command: |
            curl -s "https://get.sdkman.io?rcupdate=false" | bash
            echo -e '\nsource "/root/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
      - run: sdk version
      - run: sdk install sbt $SBT_VERSION
      - run:
          name: SBT Assembly
          no_output_timeout: 30m
          command: sbt assembly
      - persist_to_workspace:
          root: .
          paths: .
workflows:
  version: 2
  build:
    jobs:
      - pre-integration-build